### ISSUE TITLE
CONUS Search Constraint Update

### ISSUE THREAD

**Issue by Jack-Hayes** [uw-cryo/coincident#7]
ValueError: Requested search polygon not within Continental U.S. or Alaska

Is returned if the search polygon extent is beyond CONUS/Alaska, even if a majority of that polygon is within CONUS/Alaska. Might want to change so that search polygon is valid if intersects with CONUS/Alaska (even if some of the extent is outside)

**Comment by Jack-Hayes** [comment]
gf_tdx = coincident.search.search(dataset='tdx')
ArrowInvalid: cannot mix list and non-list, non-null values

Also getting this when searching the entire dataset, I think we just need to update STAC collection parsing to ensure consistent datatypes before converting to geopandas

**Comment by scottyhq** [comment]
> Might want to change so that search polygon is valid if intersects with CONUS/Alaska (even if some of the extent is outside)

Agreed! I was on the fence on including any sort of pre-search validation in the first place. Also would be fine to just remove it!

> gf_tdx = coincident.search.search(dataset='tdx')
ArrowInvalid: cannot mix list and non-list, non-null values

Let's open a separate issue for this

**Comment by scottyhq** [comment]
closed by #10!
